---
jellyfin_ffmpeg_package_url: https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.1.3-1/amd64/jellyfin-ffmpeg7_7.1.3-1-trixie_amd64.deb
jellyfin_server_package_url: https://repo.jellyfin.org/files/server/debian/stable/v10.11.4/amd64/jellyfin-server_10.11.4+deb13_amd64.deb
jellyfin_web_package_url: https://repo.jellyfin.org/files/server/debian/stable/v10.11.4/amd64/jellyfin-web_10.11.4+deb13_all.deb
